version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.dokka
    versions:
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.30
    - 1.4.31
  - dependency-name: io.kotest:kotest-runner-junit5-jvm
    versions:
    - 4.4.1
  - dependency-name: io.kotest:kotest-extensions-testcontainers-jvm
    versions:
    - 4.4.0
    - 4.4.1
  - dependency-name: io.kotest:kotest-plugins-pitest
    versions:
    - 4.4.0
    - 4.4.1
  - dependency-name: io.kotest:kotest-assertions-core-jvm
    versions:
    - 4.4.0
    - 4.4.1
  - dependency-name: io.kotest:kotest-property-jvm
    versions:
    - 4.4.0
    - 4.4.1
